//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilahiyyat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mecidEntities : DbContext
    {
        public mecidEntities()
            : base("name=mecidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pillar> Pillar { get; set; }
        public virtual DbSet<Sermon> Sermon { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
    }
}
